Traceback (most recent call last):
  File "quadtree_table.py", line 79, in <module>
    tree = CQuadTree(rootnode, resolution)
  File "quadtree_table.py", line 67, in __init__
    QuadTree.__init__(self, rootnode, minrect)
  File "/home/spmuppar/TranscriticalFlame/ThermoTableGeneration/src/quadtree.py", line 88, in __init__
    rootnode.subdivide() # constructs the network of nodes
  File "/home/spmuppar/TranscriticalFlame/ThermoTableGeneration/src/quadtree.py", line 59, in subdivide
    span = self.spans_feature(rects[n], rects_rhoe[n], self.depth) #for each child, check if it spans a feature
  File "quadtree_table.py", line 40, in spans_feature
    dataNIST=NIST.readNIST(isoType = "isotherm", fluid = 'O2', T=x_mid, P=z_mid/1.0E6, tmin=x_mid, tmax=x_mid, pmin = z_mid/1.0E6, pmax = z_mid/1.0E6, N=1)
  File "/home/spmuppar/TranscriticalFlame/ThermoTableGeneration/src/NIST_reader.py", line 24, in readNIST
    return readNISTWebsite(website)
  File "/home/spmuppar/TranscriticalFlame/ThermoTableGeneration/src/NIST_reader.py", line 87, in readNISTWebsite
    doc = session.get(website)
  File "/home/spmuppar/python/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 483, in get
    return self.request('GET', url, **kwargs)
  File "/home/spmuppar/python/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/spmuppar/python/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "/home/spmuppar/python/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='webbook.nist.gov', port=80): Max retries exceeded with url: /cgi/fluid.cgi?Action=Data&Wide=on&ID=C7782447&Type=IsoTherm&Digits=5&PLow=0.08005&PHigh=0.08005&PInc=0.0&T=300&RefState=DEF&TUnit=K&PUnit=MPa&DUnit=kg%2Fm3&HUnit=kJ%2Fkg&WUnit=m%2Fs&VisUnit=Pa*s&STUnit=N%2Fm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2afaec47c9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
--- SharcNET Job Epilogue ---
              job id: 9204652
         exit status: 1
            cpu time: 1s / 120s (0 %)
        elapsed time: 18s / 120s (15 %)
      virtual memory: 644.7M / 1.0G (62 %)

Job returned with status 1.
WARNING: Job only used 15 % of its requested walltime.
WARNING: Job only used 0 % of its requested cpu time.
WARNING: Job only used 5 % of allocated cpu time.
WARNING: Job only used 62% of its requested memory.
